allowBuilds:
  '@tailwindcss/oxide': true
  core-js: set this to true or false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@unified-heatmap/core@0.1.0 || 0.1.1'
  - '@unified-heatmap/react@0.1.0 || 0.1.1'
